# Source: retail-store-sample-orders-chart/templates/secret-db.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "b3JkZXJz"
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "YlZ1cks3WnUzaWJBU3VMSg=="
