apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default-instrumentation
  namespace: default
spec:
  # ============ GLOBAL ENV (applies to all languages) ============
  env:
    # Enable SDK
    - name: OTEL_SDK_DISABLED
      value: "false"

    # Use OTLP over HTTP/protobuf
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"

    # Enable AWS resource detection (EKS, EC2 metadata etc.)
    - name: OTEL_RESOURCE_PROVIDERS_AWS_ENABLED
      value: "true"

    # Export only TRACES for now (no metrics/logs)
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"

    # Disable metrics export for now (no metrics pipeline yet)
    - name: OTEL_METRICS_EXPORTER
      value: "none"

    # Explicitly disable logs export
    - name: OTEL_LOGS_EXPORTER
      value: "none"

  # OTLP endpoint for all auto-instrumented apps
  exporter:
    endpoint: http://adot-traces-collector:4318

  # ============ Cross-service tracing config =====================
  propagators:
    - tracecontext
    - baggage

  sampler:
    type: always_on
