apiVersion: v1
kind: Pod
metadata:
  name: checkout-redis-client
  namespace: default
spec:
  # Use the same ServiceAccount that has Pod Identity access
  serviceAccountName: checkout
  containers:
  - name: redis-client
    image: redis:7.2
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]

    env:
      # Fetch Redis endpoint from ConfigMap
      - name: REDIS_URL
        valueFrom:
          configMapKeyRef:
            name: checkout
            key: RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL
  restartPolicy: Never
