apiVersion: v1
kind: Pod
metadata:
  name: orders-postgresql-client
  namespace: default
spec:
  # Use the same ServiceAccount that has Pod Identity access
  serviceAccountName: orders
  containers:
  - name: psql-client
    image: postgres:17.6
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]

    env:
      # ✅ Fetch credentials securely from synced Secret
      - name: PGUSER
        valueFrom:
          secretKeyRef:
            name: orders-db
            key: RETAIL_ORDERS_PERSISTENCE_USERNAME

      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: orders-db
            key: RETAIL_ORDERS_PERSISTENCE_PASSWORD

      # Fetch DB endpoint and name from ConfigMap
      - name: PGHOST
        valueFrom:
          configMapKeyRef:
            name: orders
            key: RETAIL_ORDERS_PERSISTENCE_ENDPOINT

      - name: PGDATABASE
        valueFrom:
          configMapKeyRef:
            name: orders
            key: RETAIL_ORDERS_PERSISTENCE_NAME

  restartPolicy: Never
