# Source: retail-store-sample-orders-chart/templates/rabbitmq-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orders-rabbitmq
data:
  RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME: Z3Vlc3Q=      
  RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: Z3Vlc3Q=      