apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-db-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: us-east-1
    usePodIdentity: "true"
    objects: |
      - objectName: "retailstore-db-secret-1"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
    
  secretObjects:
    - secretName: orders-db
      type: Opaque
      data:
        - objectName: username
          key: RETAIL_ORDERS_PERSISTENCE_USERNAME
        - objectName: password
          key: RETAIL_ORDERS_PERSISTENCE_PASSWORD