apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts
  labels:
    app.kubernetes.io/name: carts
    app.kubernetes.io/instance: carts
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
